# Generated by Django 3.2 on 2021-04-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20210429_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='url',
        ),
        migrations.AddField(
            model_name='website',
            name='domain',
            field=models.CharField(default='hey', max_length=255, unique=True, verbose_name='Website Doamin'),
            preserve_default=False,
        ),
    ]
