# Generated by Django 3.2 on 2021-04-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_website_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='domain',
            field=models.CharField(max_length=255, unique=True, verbose_name='Website Domain'),
        ),
    ]
