# Generated by Django 3.2 on 2021-04-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_alter_website_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='name',
            new_name='title',
        ),
    ]
