# Generated by Django 3.2 on 2021-04-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0008_website_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(default='hey', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
