# Generated by Django 3.2 on 2021-05-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_alter_website_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='domain',
            field=models.CharField(help_text='Website URL i.e. - https://example.com/', max_length=255, unique=True, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(help_text='Give a title to this website.', max_length=255, verbose_name='Website title'),
        ),
    ]
