# Generated by Django 3.2 on 2021-05-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0010_auto_20210501_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='domain',
            new_name='url',
        ),
    ]
