# Generated by Django 3.2 on 2021-05-04 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websites', '0013_alter_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_cb', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
