# Generated by Django 3.2 on 2021-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='1', max_length=2),
            preserve_default=False,
        ),
    ]
