# Generated by Django 3.2 on 2021-04-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_alter_website_title'),
        ('core', '0002_notification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='fcm_token',
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(verbose_name='Notification Body'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('1', 'SUCCESS'), ('2', 'FAIL'), ('3', 'PENDING')], default='3', max_length=2, verbose_name='Notification Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Notification Title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website', verbose_name='Website'),
        ),
    ]
