# Generated by Django 3.2 on 2021-04-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210429_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('1', 'SUCCESS'), ('2', 'FAIL'), ('3', 'PENDING')], default='3', editable=False, max_length=2, verbose_name='Notification Status'),
        ),
    ]
