# Generated by Django 3.2 on 2021-04-30 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_alter_website_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_fcmdevicetoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FCMDeviceToken',
            new_name='FCMTokenDevice',
        ),
        migrations.AlterModelOptions(
            name='fcmtokendevice',
            options={'verbose_name': 'FCM Token Device', 'verbose_name_plural': 'FCM Token Devices'},
        ),
    ]
