# Generated by Django 3.2 on 2021-05-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0008_chordcounter'),
        ('core', '0009_auto_20210501_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='task_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult'),
            preserve_default=False,
        ),
    ]
