# Generated by Django 3.2 on 2021-05-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_notification_task_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_on',), 'verbose_name': 'Notification History', 'verbose_name_plural': 'Notification Histories'},
        ),
        migrations.AddField(
            model_name='notification',
            name='failure_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Failed to Sent Count'),
        ),
        migrations.AddField(
            model_name='notification',
            name='success_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Successfully Sent Count'),
        ),
    ]
