# Generated by Django 3.2 on 2021-05-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210502_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='failure_count',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Failed to Sent Count'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='success_count',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Successfully Sent Count'),
        ),
    ]
