# Generated by Django 3.2 on 2021-05-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210502_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='notification_banner/%Y/%m/%d/%H:%M:%S/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='notification_icons/%Y/%m/%d/%H:%M:%S/'),
        ),
    ]
