# Generated by Django 3.2 on 2021-05-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210503_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='notification_banner/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='notification_icons/%Y/%m/%d/'),
        ),
    ]
