# Generated by Django 3.2 on 2021-05-04 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Username should be unique.', max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Username'),
        ),
    ]
